In [3]:
# Working with AQI dataset
import numpy as np
import pandas as pd

In [4]:
# Reading the data from CSV  file
df = pd.read_csv("AQI_dataset.csv")

df.head(5)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [5]:
# Selecting the data

# columns
df[["city", "aqi"]]

# rows
df.loc[2]       # prints row data
df.loc[0:2]     # start idx : end idx (inclusive)

df.iloc[2]      # prints row data
df.iloc[0:2]    # start idx : end idx (non-inclusive)

# cells - (row, col)
df.loc[0, ["city", "aqi"]]
df.loc[0:2, ["city", "aqi"]]

df.iloc[0, [2, 11]]     # index: city => 2, aqi => 11
df.iloc[0:2, [2, 11]]

# cell
df.at[0, "city"]
df.iat[0, 2]        # 2 => city index

'New York'

In [6]:
# Filtering of data => returns a view of data
df[df["aqi"] > 100]     # columns with AQI > 100
df[(df["aqi"] > 100) & (df["temperature"] > 30)]    # columns with AQI > 100 & Temp > 30

df[df["aqi"] > 100][["city", "aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [7]:
# Query method => returns a copy of data
aqi_val = 100
df.query("aqi > 100 & temperature > 30")
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]